image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

# Variables
variables:
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  # Define individual environment variables for backend DB connection
  DB_HOST: $CI_COMMIT_REF_NAME  # Example, customize as needed
  DB_PORT: $CI_COMMIT_REF_NAME  # Example, customize as needed
  DB_USER: $CI_COMMIT_REF_NAME  # Example, customize as needed
  DB_PASSWORD: $CI_COMMIT_REF_NAME  # Example, customize as needed
  DB_NAME: $CI_COMMIT_REF_NAME  # Example, customize as needed
  DB_SSLMODE: $CI_COMMIT_REF_NAME  # Example, customize as needed

# Build Frontend
build_frontend:
  stage: build
  script:
    - echo "Building frontend Docker image..."
    - docker build -f frontend/Dockerfile -t $FRONTEND_IMAGE .
    - docker push $FRONTEND_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"

# Build Backend
build_backend:
  stage: build
  script:
    - echo "Building backend Docker image..."
    - docker build -f backend/Dockerfile -t $BACKEND_IMAGE .
    - docker push $BACKEND_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"

# Deploy to GitLab Pages
deploy:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
    - export DB_CONNECTION_STRING="host=$DB_HOST port=$DB_PORT user=$DB_USER password=$DB_PASSWORD dbname=$DB_NAME sslmode=$DB_SSLMODE"
    - echo "DB Connection String: $DB_CONNECTION_STRING"  # Optional: for debugging
    - mkdir -p public
    - docker run --rm -e DB_CONNECTION_STRING=$DB_CONNECTION_STRING $FRONTEND_IMAGE sh -c "tar -cf - /usr/share/nginx/html | tar -xf - -C public --strip-components=3"
    - cp -r backend/bin/* public/api  # Ensure API is served under /api
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"