image: 'docker:latest'
services:
  - 'docker:dind'
stages:
  - build
  - deploy
variables:
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  DB_HOST: $CI_COMMIT_REF_NAME
  DB_PORT: $CI_COMMIT_REF_NAME
  DB_USER: $CI_COMMIT_REF_NAME
  DB_PASSWORD: $CI_COMMIT_REF_NAME
  DB_NAME: $CI_COMMIT_REF_NAME
  DB_SSLMODE: $CI_COMMIT_REF_NAME

# Define the cache settings for node_modules to speed up the build process
cache:
  paths:
    - frontend/node_modules/

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_frontend:
  stage: build
  script:
    - echo "Setting PUBLIC_URL..."
    - export PUBLIC_URL="https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/file/public"
    - echo "PUBLIC_URL is set to: $PUBLIC_URL"
    - echo "Building frontend Docker image..."
    - docker build -f frontend/Dockerfile --build-arg PUBLIC_URL=$PUBLIC_URL -t $FRONTEND_IMAGE .
    - docker push $FRONTEND_IMAGE
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

build_backend:
  stage: build
  script:
    - echo "Building backend Docker image..."
    - docker build -f backend/Dockerfile -t $BACKEND_IMAGE .
    - docker push $BACKEND_IMAGE
    - echo "Extracting backend binary from the Docker image..."
    - mkdir -p backend/bin
    - docker create --name temp-container $BACKEND_IMAGE
    - docker cp temp-container:/app/main backend/bin/main
    - docker rm temp-container
  artifacts:
    paths:
      - backend/bin
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy:
  stage: deploy
  dependencies:
    - build_backend
    - build_frontend  # Ensure this job runs after build_frontend
  script:
    - echo "Deploying to GitLab Pages..."
    - mkdir -p public  # Create the public directory on the host
    - docker run --rm -v "$(pwd)/public:/public" $FRONTEND_IMAGE sh -c "cd /app/build && tar -cf - . | tar -xf - -C /public"
    - cp -r backend/bin/* public/api  # Copy backend files if needed
  artifacts:
    paths:
      - public  # Save the public directory as an artifact
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
