stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $DOCKER_REGISTRY/rezav/rezaverse/frontend

before_script:
  - echo "Setting up Docker..."
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY

# Build Frontend Docker Image
build_frontend:
  stage: build
  image: node:18  # Use Node.js image for React
  services:
    - docker:dind  # Use Docker-in-Docker
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building React app..."
    - npm run build
    - echo "Building Docker image..."
    - >
      docker build \
        --build-arg REACT_APP_API_URL="https://rezav.gitlab.io/rezaverse/api" \
        --build-arg REACT_APP_DOMAIN_NAME="https://rezav.gitlab.io/rezaverse" \
        -t $FRONTEND_IMAGE ./frontend
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push $FRONTEND_IMAGE

# Deploy to GitLab Pages
pages:
  stage: deploy
  image: alpine:latest  # Use a lightweight image for deployment
  script:
    - echo "Deploying frontend to GitLab Pages..."
    - mkdir -p public  # Ensure the public directory exists
    - cp -r frontend/build/* public/  # Copy built files to public/
  artifacts:
    paths:
      - public  # GitLab Pages serves the contents of the public folder
  only:
    - main  # Adjust this if you're working with a different branch like `develop`