stages:
  - build

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $DOCKER_REGISTRY/rezav/rezaverse/frontend

before_script:
  - echo "Setting up Docker..."
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY

# Build Frontend Docker Image
build_frontend:
  stage: build
  image: docker:latest  # Use the Docker image
  services:
    - docker:dind  # Use Docker-in-Docker
  script:
    - echo "Building frontend Docker image..."
    - >
      docker build \
        --build-arg REACT_APP_API_URL="https://rezav.gitlab.io/rezaverse/api" \
        --build-arg REACT_APP_DOMAIN_NAME="https://rezav.gitlab.io/rezaverse" \
        -t $FRONTEND_IMAGE ./frontend
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push $FRONTEND_IMAGE
# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r frontend/build/* public/
  artifacts:
    paths:
      - public
  only:
    - main