image: docker:latest

services:
  - docker:dind

stages: 
  - build_backend
  - deploy_backend
  - build_frontend
  - deploy_frontend

variables:
  DEPLOY_FRONTEND: "true"
  DEPLOY_BACKEND: "true"
  CI_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/frontend
  BACKEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/backend

# Cache node_modules for frontend
cache:
  paths:
    - frontend/node_modules/

# Debugging Stage


# Build Backend Docker Image
build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image..."
    - docker build -t $BACKEND_IMAGE ./backend
    - docker push $BACKEND_IMAGE
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'

# Build Frontend Docker Image
build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend Docker image..."
    - >
      docker build \
        --build-arg REACT_APP_API_URL="https://rezav.gitlab.io/rezaverse/api" \
        --build-arg REACT_APP_DOMAIN_NAME="https://rezav.gitlab.io/rezaverse" \
        -t $FRONTEND_IMAGE ./frontend
    - echo "Pushing frontend Docker image to GitLab Container Registry..."
    - docker push $FRONTEND_IMAGE
  rules:
    - if: '$DEPLOY_FRONTEND == "true" || $CI_COMMIT_REF_NAME == "main"'

# Deploy Backend
deploy_backend:
  stage: deploy_backend
  script:
    - echo "Deploying backend..."
    # Add your backend deployment script here
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'

# Deploy Frontend to GitLab Pages
deploy_frontend:
  stage: deploy_frontend
  script:
    - echo "Deploying frontend to GitLab Pages..."
    - mkdir -p public
    - docker run --rm $FRONTEND_IMAGE tar -cf - /usr/share/nginx/html | tar -xf - -C public --strip-components=3
  artifacts:
    paths:
      - public
  rules:
    - if: '$DEPLOY_FRONTEND == "true" || $CI_COMMIT_REF_NAME == "main"'
