image: docker:latest

services:
  - docker:dind

before_script:
  - echo "Setting up Docker and Node.js..."
  - apk add --no-cache nodejs npm  # Install Node.js and npm
  - npm install -g npm@latest      # Update npm to the latest version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REGISTRY

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $DOCKER_REGISTRY/rezav/rezaverse/frontend

build_frontend:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building React app..."
    - npm run build
    - echo "Building Docker image..."
    - >
      docker build \
        --build-arg REACT_APP_API_URL="https://rezav.gitlab.io/rezaverse/api" \
        --build-arg REACT_APP_DOMAIN_NAME="https://rezav.gitlab.io/rezaverse" \
        -t $FRONTEND_IMAGE ./frontend
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push $FRONTEND_IMAGE

pages:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying frontend to GitLab Pages..."
    - mkdir -p public
    - cp -r frontend/build/* public/
  artifacts:
    paths:
      - public
  only:
    - main