image: docker:latest

services:
  - docker:dind

before_script:
  - echo "Setting up Docker..."
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build_frontend
  - build_backend
  - deploy_frontend
  - deploy_backend

# Define the DEPLOY_FRONTEND variable internally (set to false by default)
variables:
  DEPLOY_FRONTEND: "false"  # Frontend deployment is disabled by default
  DEPLOY_BACKEND: "true"    # Backend deployment is enabled by default
  CI_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/frontend
  BACKEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/backend

# Debug: Print the value of DEPLOY_FRONTEND and DEPLOY_BACKEND
debug_flags:
  stage: build_frontend
  script:
    - echo "DEPLOY_FRONTEND is set to: $DEPLOY_FRONTEND"
    - echo "DEPLOY_BACKEND is set to: $DEPLOY_BACKEND"
    - echo "CI_REGISTRY is set to: $CI_REGISTRY"
    - echo "FRONTEND_IMAGE is set to: $FRONTEND_IMAGE"
    - echo "BACKEND_IMAGE is set to: $BACKEND_IMAGE"
  rules:
    - if: '$DEPLOY_FRONTEND == "true" || $DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Build Frontend Docker Image
build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend Docker image..."
    - >
      docker build \
        --build-arg REACT_APP_API_URL="https://rezav.gitlab.io/rezaverse/api" \
        --build-arg REACT_APP_DOMAIN_NAME="https://rezav.gitlab.io/rezaverse" \
        -t $FRONTEND_IMAGE ./frontend
    - echo "Pushing frontend Docker image to GitLab Container Registry..."
    - docker push $FRONTEND_IMAGE
  rules:
    - if: '$DEPLOY_FRONTEND == "true"'
      when: always
    - when: never

# Build Backend Docker Image
build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image..."
    - >
      docker build \
        --build-arg API_PORT="8080" \
        --build-arg STATIC_PATH="/app/dist" \
        --build-arg DB_HOST="db-shopa-do-user-10123840-0.b.db.ondigitalocean.com" \
        --build-arg DB_PORT="25060" \
        -t $BACKEND_IMAGE ./backend
    - echo "Pushing backend Docker image to GitLab Container Registry..."
    - docker push $BACKEND_IMAGE
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Deploy Frontend to GitLab Pages
deploy_frontend:
  stage: deploy_frontend
  script:
    - echo "Deploying frontend to GitLab Pages..."
    - mkdir -p public
    - docker run --rm $FRONTEND_IMAGE tar -cf - /usr/share/nginx/html | tar -xf - -C public
  artifacts:
    paths:
      - public
  rules:
    - if: '$DEPLOY_FRONTEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Deploy Backend (Example: Deploy to Kubernetes or another platform)
deploy_backend:
  stage: deploy_backend
  script:
    - echo "Deploying backend..."
    # Add your backend deployment script here (e.g., deploy to Kubernetes, DigitalOcean, etc.)
    # Example:
    # kubectl apply -f backend-deployment.yaml
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never