image: docker:latest

services:
  - docker:dind

stages:
  - build_backend
  - deploy_backend
  - build_frontend
  - deploy_frontend

variables:
  DEPLOY_FRONTEND: "true"
  DEPLOY_BACKEND: "true"
  CI_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/frontend
  BACKEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/backend

# Cache node_modules for frontend
cache:
  paths:
    - frontend/node_modules/

# Debugging Stage
debug:
  stage: build_backend
  script:
    - echo "DEPLOY_FRONTEND: $DEPLOY_FRONTEND"
    - echo "DEPLOY_BACKEND: $DEPLOY_BACKEND"

# Build Backend Docker Image
build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image..."
    - docker build -t $BACKEND_IMAGE ./backend
    - docker push $BACKEND_IMAGE
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'

# Build Frontend Docker Image
build_frontend:
  stage: build_frontend
