image: docker:latest

services:
  - docker:dind

before_script:
  - echo "Setting up Docker..."
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build_frontend
  - build_backend
  - deploy_frontend
  - deploy_backend

variables:
  DEPLOY_FRONTEND: "true"
  DEPLOY_BACKEND: "true"
  CI_REGISTRY: registry.gitlab.com
  FRONTEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/frontend
  BACKEND_IMAGE: $CI_REGISTRY/rezav/rezaverse/backend

cache:
  paths:
    - node_modules/

# Debug: Print the value of DEPLOY_FRONTEND and DEPLOY_BACKEND
debug_flags:
  stage: build_frontend
  script:
    - |
      echo "DEPLOY_FRONTEND is set to: $DEPLOY_FRONTEND"
      echo "DEPLOY_BACKEND is set to: $DEPLOY_BACKEND"
      echo "CI_REGISTRY is set to: $CI_REGISTRY"
      echo "FRONTEND_IMAGE is set to: $FRONTEND_IMAGE"
      echo "BACKEND_IMAGE is set to: $BACKEND_IMAGE"
  rules:
    - if: '$DEPLOY_FRONTEND == "true" || $DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Debug: List files in the repository
debug_files:
  stage: build_backend
  script:
    - echo "Listing files in the repository..."
    - ls -R
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Build Frontend
build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend..."
    - rm -rf build
    - CI=false npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: '$DEPLOY_FRONTEND == "true"'
      when: always
    - when: never

# Build Backend
build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image..."
    - >
      docker build \
        --build-arg API_PORT="8080" \
        --build-arg STATIC_PATH="/app/dist" \
        --build-arg DB_HOST="db-shopa-do-user-10123840-0.b.db.ondigitalocean.com" \
        --build-arg DB_PORT="25060" \
        -t $BACKEND_IMAGE ./backend
    - echo "Pushing backend Docker image to GitLab Container Registry..."
    - docker push $BACKEND_IMAGE
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Deploy Frontend to GitLab Pages
deploy_frontend:
  stage: deploy_frontend
  script:
    - echo "Deploying frontend to GitLab Pages..."
    - ls public
  artifacts:
    paths:
      - public
  rules:
    - if: '$DEPLOY_FRONTEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never

# Deploy Backend
deploy_backend:
  stage: deploy_backend
  script:
    - echo "Deploying backend..."
    # Add your backend deployment script here
  rules:
    - if: '$DEPLOY_BACKEND == "true" || $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never